# Generated by Django 6.0.2 on 2026-02-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="requested_role",
            field=models.CharField(
                choices=[("instructor", "강사"), ("member", "일반 회원")],
                default="member",
                help_text="회원가입 시 신청한 역할",
                max_length=20,
                verbose_name="요청 역할",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "관리자"),
                    ("instructor", "강사"),
                    ("member", "일반 회원"),
                    ("pending", "승인대기"),
                ],
                default="pending",
                max_length=20,
                verbose_name="역할",
            ),
        ),
    ]
