# Generated by Django 5.2.11 on 2026-02-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_requested_role_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("code", models.CharField(max_length=6, verbose_name="인증 코드")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="인증 완료"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="만료일")),
            ],
            options={
                "verbose_name": "이메일 인증",
                "verbose_name_plural": "이메일 인증 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="이메일 인증 여부"),
        ),
        migrations.AddField(
            model_name="user",
            name="social_provider",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="소셜 로그인 제공자"
            ),
        ),
    ]
