# Generated by Django 5.2.11 on 2026-02-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailverification_user_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="사용자 이름", max_length=150, verbose_name="이름"
            ),
        ),
    ]
