# Generated by Django 5.2.11 on 2026-02-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_allow_korean_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
