# Generated by Django 5.2.11 on 2026-03-27 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_managers"),
        ("messenger", "0005_chatroommembership_last_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_members",
                to="messenger.chatroom",
                verbose_name="배정 클럽",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="wants_club_membership",
            field=models.BooleanField(default=False, verbose_name="클럽 가입 희망"),
        ),
        migrations.AlterField(
            model_name="user",
            name="requested_role",
            field=models.CharField(
                choices=[("instructor", "클럽장"), ("member", "일반 회원")],
                default="member",
                help_text="회원가입 시 신청한 역할",
                max_length=20,
                verbose_name="요청 역할",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "관리자"),
                    ("instructor", "클럽장"),
                    ("member", "일반 회원"),
                    ("pending", "승인대기"),
                ],
                default="pending",
                max_length=20,
                verbose_name="역할",
            ),
        ),
    ]
