# Generated by Django 5.2.12 on 2026-04-13 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messenger', '0008_clubimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('msg_type', models.CharField(choices=[('SMS', 'SMS'), ('LMS', 'LMS')], default='SMS', max_length=3, verbose_name='메시지 유형')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='수신자 수')),
                ('recipients_info', models.JSONField(blank=True, default=list, verbose_name='수신자 정보')),
                ('aligo_response', models.JSONField(blank=True, default=dict, verbose_name='Aligo 응답')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='messenger.chatroom', verbose_name='클럽')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='발송자')),
            ],
            options={
                'verbose_name': 'SMS 발송 로그',
                'verbose_name_plural': 'SMS 발송 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
