# Generated by Django 6.0.2 on 2026-02-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("match", "정기 경기"),
                            ("tournament", "토너먼트"),
                            ("practice", "연습"),
                            ("meeting", "모임"),
                            ("other", "기타"),
                        ],
                        default="match",
                        max_length=20,
                        verbose_name="일정 유형",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="장소"),
                ),
                ("start_date", models.DateTimeField(verbose_name="시작 일시")),
                ("end_date", models.DateTimeField(verbose_name="종료 일시")),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=0, verbose_name="최대 참가자 수"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "일정",
                "verbose_name_plural": "일정 목록",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("confirmed", "확정"),
                            ("cancelled", "취소"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청일"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="schedule.event",
                        verbose_name="일정",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="참가자",
                    ),
                ),
            ],
            options={
                "verbose_name": "참가자",
                "verbose_name_plural": "참가자 목록",
                "unique_together": {("event", "user")},
            },
        ),
    ]
