# Generated by Django 5.2.12 on 2026-04-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_link',
            field=models.URLField(blank=True, help_text='네이버지도, 구글맵 등 링크', max_length=500, verbose_name='장소 링크'),
        ),
    ]
