# Generated by Django 5.2.12 on 2026-04-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_event_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', '공용'), ('member', '회원 전용')], default='member', max_length=10, verbose_name='노출 범위'),
        ),
    ]
