# Generated by Django 5.2.12 on 2026-04-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_event_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': '일정', 'verbose_name_plural': '일정 목록'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_popup',
            field=models.BooleanField(default=False, verbose_name='팝업 표시'),
        ),
    ]
