# Generated by Django 6.0.2 on 2026-02-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gallery/covers/",
                        verbose_name="커버 이미지",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="공개 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "앨범",
                "verbose_name_plural": "앨범 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="gallery/photos/", verbose_name="이미지"
                    ),
                ),
                (
                    "caption",
                    models.CharField(blank=True, max_length=200, verbose_name="설명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="gallery.album",
                        verbose_name="앨범",
                    ),
                ),
            ],
            options={
                "verbose_name": "사진",
                "verbose_name_plural": "사진 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
