# Generated by Django 6.0.2 on 2026-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="album_type",
            field=models.CharField(
                choices=[("public", "공용 갤러리"), ("member", "회원 전용 갤러리")],
                default="public",
                max_length=20,
                verbose_name="앨범 유형",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="숨김"),
        ),
        migrations.AddField(
            model_name="photo",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="숨김"),
        ),
    ]
