# Generated by Django 5.2.12 on 2026-04-28 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_album_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '갤러리 카테고리',
                'verbose_name_plural': '갤러리 카테고리 목록',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='gallery.gallerycategory', verbose_name='카테고리'),
        ),
    ]
