# Generated by Django 5.2.12 on 2026-04-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallerycategory_album_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', 'created_at'], 'verbose_name': '사진', 'verbose_name_plural': '사진 목록'},
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬 순서'),
        ),
    ]
