# Generated by Django 5.2.12 on 2026-04-30 05:05

from django.db import migrations


def assign_photo_order(apps, schema_editor):
    Photo = apps.get_model('gallery', 'Photo')
    Album = apps.get_model('gallery', 'Album')
    for album in Album.objects.all():
        photos = Photo.objects.filter(album=album).order_by('created_at')
        for i, photo in enumerate(photos):
            photo.order = i
            photo.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_photo_options_photo_order'),
    ]

    operations = [
        migrations.RunPython(assign_photo_order, migrations.RunPython.noop),
    ]
