# Generated by Django 6.0.2 on 2026-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="숨김"),
        ),
    ]
