# Generated by Django 5.2.11 on 2026-02-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0002_notice_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="visibility",
            field=models.CharField(
                choices=[("public", "공용 (비로그인 가능)"), ("member", "회원 전용")],
                default="member",
                max_length=20,
                verbose_name="노출 범위",
            ),
        ),
    ]
