# Generated by Django 5.2.11 on 2026-03-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0003_notice_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="배너 이미지"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="전화번호"),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="간단 문구"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "배너",
                "verbose_name_plural": "배너 목록",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="기관명")),
                (
                    "logo",
                    models.ImageField(upload_to="organizations/", verbose_name="로고"),
                ),
                ("link", models.URLField(verbose_name="링크")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
            ],
            options={
                "verbose_name": "유관기관",
                "verbose_name_plural": "유관기관 목록",
                "ordering": ["order"],
            },
        ),
    ]
