# Generated by Django 5.2.12 on 2026-04-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_banner_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.TextField(blank=True, default='', verbose_name='인사말 텍스트')),
                ('greeting_author', models.CharField(blank=True, default='대덕구골프협회장', max_length=100, verbose_name='인사말 서명')),
                ('greeting_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='인사말 이미지')),
                ('members_text', models.TextField(blank=True, default='', verbose_name='협회인원 텍스트')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '협회소개 콘텐츠',
                'verbose_name_plural': '협회소개 콘텐츠',
            },
        ),
    ]
