# Generated by Django 5.2.12 on 2026-04-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='전화번호')),
                ('greeting', models.TextField(blank=True, default='', verbose_name='인사말')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='executives/', verbose_name='프로필 사진')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '협회 임원',
                'verbose_name_plural': '협회 임원 목록',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='aboutcontent',
            name='members_text',
        ),
    ]
