# Generated by Django 5.2.12 on 2026-04-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_chatroom_icon'),
        ('notices', '0006_executive_remove_aboutcontent_members_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_notices', to='messenger.chatroom', verbose_name='클럽'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='visibility',
            field=models.CharField(choices=[('public', '공용 (비로그인 가능)'), ('member', '회원 전용'), ('club', '클럽 전용')], default='member', max_length=20, verbose_name='노출 범위'),
        ),
    ]
