# Generated by Django 5.2.12 on 2026-04-06 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_chatroom_icon'),
        ('notices', '0007_notice_club_alter_notice_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_notices', to='messenger.chatroom', verbose_name='클럽'),
        ),
    ]
