# Generated by Django 5.2.12 on 2026-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_alter_notice_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='링크'),
        ),
    ]
