# Generated by Django 5.2.12 on 2026-04-15 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0009_banner_link'),
        ('schedule', '0003_event_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('content', models.CharField(max_length=500, verbose_name='내용')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '연혁',
                'verbose_name_plural': '연혁 목록',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='is_popup',
            field=models.BooleanField(default=False, verbose_name='팝업 표시'),
        ),
        migrations.AddField(
            model_name='notice',
            name='linked_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popup_notices', to='schedule.event', verbose_name='연결 경기일정'),
        ),
        migrations.AddField(
            model_name='notice',
            name='popup_content',
            field=models.TextField(blank=True, default='', verbose_name='팝업 문구'),
        ),
        migrations.AddField(
            model_name='notice',
            name='popup_image',
            field=models.ImageField(blank=True, null=True, upload_to='popup/', verbose_name='팝업 이미지'),
        ),
    ]
