# Generated by Django 5.2.12 on 2026-04-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0010_history_notice_is_popup_notice_linked_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='detail',
            field=models.TextField(blank=True, default='', verbose_name='상세 내용'),
        ),
    ]
