# Generated by Django 6.0.2 on 2026-02-09 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제됨"),
        ),
        migrations.CreateModel(
            name="ChatBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ban_type",
                    models.CharField(
                        choices=[
                            ("mute", "채팅 금지"),
                            ("kick", "강제 퇴장"),
                            ("ban", "영구 차단"),
                        ],
                        default="mute",
                        max_length=20,
                        verbose_name="제재 유형",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="제재 사유")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="제재 만료일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제재일"),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_bans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제재자",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bans",
                        to="messenger.chatroom",
                        verbose_name="채팅방",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_bans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제재 대상",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 제재",
                "verbose_name_plural": "채팅 제재 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
