# Generated by Django 6.0.2 on 2026-02-09 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_message_is_deleted_chatban"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_chat_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="생성자",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="공용 채팅방"),
        ),
    ]
