# Generated by Django 5.2.11 on 2026-02-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0004_chatroominvitation_chatroommembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroommembership",
            name="last_read_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="마지막 읽은 시간"
            ),
        ),
    ]
