# Generated by Django 5.2.12 on 2026-04-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_chatroommembership_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='club_icons/', verbose_name='클럽 아이콘'),
        ),
    ]
