# Generated by Django 5.2.12 on 2026-04-07 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_chatroom_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('join', '가입'), ('leave', '탈퇴')], max_length=10, verbose_name='요청 유형')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('approved', '승인됨'), ('rejected', '거절됨')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='응답일')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_club_requests', to=settings.AUTH_USER_MODEL, verbose_name='응답자')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='messenger.chatroom', verbose_name='클럽')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_membership_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': '클럽 가입/탈퇴 요청',
                'verbose_name_plural': '클럽 가입/탈퇴 요청 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
