# Generated by Django 5.2.12 on 2026-04-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_clubmembershiprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club_images/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_images', to='messenger.chatroom', verbose_name='클럽')),
            ],
            options={
                'verbose_name': '클럽 이미지',
                'verbose_name_plural': '클럽 이미지 목록',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
